-- MySQL Script generated by MySQL Workbench
-- Sat Dec  2 18:20:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gr_search_engine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gr_search_engine` ;

-- -----------------------------------------------------
-- Schema gr_search_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gr_search_engine` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `gr_search_engine` ;

-- -----------------------------------------------------
-- Table `gr_search_engine`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gr_search_engine`.`book` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gr_search_engine`.`book` (
  `book_id` BIGINT NOT NULL AUTO_INCREMENT,
  `gr_book_id` BIGINT NOT NULL,
  `title` TEXT NOT NULL,
  `mod_title` TEXT NOT NULL,
  `ratings_count` INT NOT NULL DEFAULT -1,
  `average_rating` DECIMAL(6,3) NOT NULL DEFAULT -1.0,
  `link` TEXT NOT NULL DEFAULT 'linkNA',
  `url` TEXT NOT NULL DEFAULT 'urlNA',
  `image_url` TEXT NOT NULL DEFAULT 'imgurlNA',
  `publication_day` TINYINT NOT NULL DEFAULT 0,
  `publication_month` TINYINT NOT NULL DEFAULT 0,
  `publication_year` INT NOT NULL DEFAULT 0,
  `num_pages` INT NOT NULL DEFAULT 0,
  `isbn` BIGINT NOT NULL DEFAULT 0,
  `isbn13` BIGINT NOT NULL DEFAULT 0,
  `description` TEXT NOT NULL DEFAULT 'descriptionNA',
  `publisher` VARCHAR(500) NOT NULL DEFAULT 'publisherNA',
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL DEFAULT 1,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL DEFAULT 1,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `i_book_id` ON `gr_search_engine`.`book` (`gr_book_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
