-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 08:37:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `books` ;

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `books` ;

-- -----------------------------------------------------
-- Table `books`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books`.`book` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `books`.`book` (
  `book_id` BIGINT NOT NULL AUTO_INCREMENT,
  `gr_book_id` BIGINT NOT NULL,
  `book_title` TEXT NOT NULL,
  `book_title_mod` TEXT NOT NULL,
  `book_title_series` TEXT NOT NULL,
  `book_title_series_mod` TEXT NOT NULL,
  `book_description` TEXT NOT NULL,
  `book_ratings_count` INT NOT NULL,
  `book_average_rating` FLOAT NOT NULL,
  `book_num_pages` INT NOT NULL,
  `book_publication_day` TINYINT NOT NULL,
  `book_publication_month` TINYINT NOT NULL,
  `book_publication_year` INT NOT NULL,
  `book_isbn` TEXT NOT NULL,
  `book_isbn13` TEXT NOT NULL,
  `book_publisher` VARCHAR(500) NOT NULL,
  `book_country_code` VARCHAR(100) NOT NULL,
  `book_language_code` VARCHAR(100) NOT NULL,
  `book_url` TEXT NOT NULL,
  `book_image_url` TEXT NOT NULL,
  `book_link` TEXT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL DEFAULT 1,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL DEFAULT 1,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `i_book_id` ON `books`.`book` (`gr_book_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
